include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types: true
    - always_put_required_named_parameters_first: true
    - always_use_package_imports: true
    - avoid_annotating_with_dynamic: true
    - avoid_dynamic_calls: true
    - avoid_print: true
    - comment_references: true
    - deprecated_member_use_from_same_package: true
    - directives_ordering: true
    - prefer_const_declarations: true
    - prefer_single_quotes: true
    - require_trailing_commas: true
    - sort_constructors_first: true
    - sort_unnamed_constructors_first: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_breaks: true
    - unnecessary_lambdas: true
    - unnecessary_null_checks: true
    - unnecessary_parenthesis: true
    - use_raw_strings: true
